[package]
name = "evaluacion-estrellas-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.evaluacion-estrellas]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.59.0"
default-features = false
